### ISSUE TITLE
Crash when running CTS `test_cl_fill_images 1Dbuffer use_pitches`

### ISSUE THREAD

**Issue by kpet** [kpet/clvk#691]
```
(gdb) bt
#0  0x00007ffff718da0d in ?? () from /usr/lib64/libc.so.6
#1  0x00007ffff76afb30 in cvk_mem::copy_from (this=0x555555983ec0, src=0x7fffa0066010, offset=0, size=7941891) at /home/kpet/repos/clvk/src/memory.hpp:240
#2  0x00007ffff770170e in cvk_command_unmap_buffer::do_action (this=0x55555743fa20) at /home/kpet/repos/clvk/src/queue.cpp:1492
#3  0x00007ffff7705864 in cvk_command::execute (this=0x55555743fa20) at /home/kpet/repos/clvk/src/queue.hpp:437
#4  0x00007ffff76fc59f in cvk_command_group::execute_cmds (this=0x555557445160) at /home/kpet/repos/clvk/src/queue.cpp:346
#5  0x00007ffff76fcd50 in cvk_executor_thread::executor (this=0x5555574416d0) at /home/kpet/repos/clvk/src/queue.cpp:460
#6  0x00007ffff77162c4 in std::__invoke_impl<void, void (cvk_executor_thread::*)(), cvk_executor_thread*> (
    __f=@0x55555640a360: (void (cvk_executor_thread::*)(cvk_executor_thread * const)) 0x7ffff76fcb5e <cvk_executor_thread::executor()>, __t=@0x55555640a358: 0x5555574416d0)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/invoke.h:74
#7  0x00007ffff7716217 in std::__invoke<void (cvk_executor_thread::*)(), cvk_executor_thread*> (__fn=@0x55555640a360: (void (cvk_executor_thread::*)(cvk_executor_thread * const)) 0x7ffff76fcb5e <cvk_executor_thread::executor()>)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/invoke.h:96
#8  0x00007ffff7716177 in std::thread::_Invoker<std::tuple<void (cvk_executor_thread::*)(), cvk_executor_thread*> >::_M_invoke<0ul, 1ul> (this=0x55555640a358) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_thread.h:292
#9  0x00007ffff771612c in std::thread::_Invoker<std::tuple<void (cvk_executor_thread::*)(), cvk_executor_thread*> >::operator() (this=0x55555640a358) at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_thread.h:299
#10 0x00007ffff771610c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<void (cvk_executor_thread::*)(), cvk_executor_thread*> > >::_M_run (this=0x55555640a350)
    at /usr/lib/gcc/x86_64-pc-linux-gnu/13/include/g++-v13/bits/std_thread.h:244
#11 0x00007ffff72e2483 in ?? () from /usr/lib/gcc/x86_64-pc-linux-gnu/13/libstdc++.so.6
#12 0x00007ffff70a7861 in ?? () from /usr/lib64/libc.so.6
#13 0x00007ffff712544c in ?? () from /usr/lib64/libc.so.6
```

**Comment by 82157402** [comment]
It is stil crash on  NVIDIA GeForce RTX 5080
<img width="1586" height="1150" alt="Image" src="https://github.com/user-attachments/assets/26fd0e3d-6639-4708-b5c3-ca5f7e5e867a" />
